"""create learning core

Revision ID: 07c1eea39ee6
Revises: 
Create Date: 2026-09-02 06:41:11.276043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07c1eea39ee6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_tracks')),
    sa.UniqueConstraint('slug', name=op.f('uq_learning_tracks_slug'))
    )
    op.create_table('learning_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_learning_modules_positive_position')),
    sa.ForeignKeyConstraint(['track_id'], ['learning_tracks.id'], name=op.f('fk_learning_modules_track_id_learning_tracks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_modules')),
    sa.UniqueConstraint('track_id', 'position', name='track_position'),
    sa.UniqueConstraint('track_id', 'slug', name='track_slug')
    )
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_concepts_positive_position')),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], name=op.f('fk_concepts_module_id_learning_modules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts')),
    sa.UniqueConstraint('module_id', 'position', name='module_position'),
    sa.UniqueConstraint('module_id', 'slug', name='module_slug')
    )
    op.create_table('concept_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery_level', sa.String(length=32), server_default=sa.text("'unseen'"), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes_markdown', sa.Text(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mastery_level IN ('unseen', 'learning', 'practicing', 'proficient', 'mastered')", name=op.f('ck_concept_mastery_valid_mastery_level')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_concept_mastery_score_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_concept_mastery_concept_id_concepts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_mastery')),
    sa.UniqueConstraint('concept_id', name=op.f('uq_concept_mastery_concept_id'))
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'planned'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'abandoned')", name=op.f('ck_learning_sessions_valid_status')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_learning_sessions_completion_after_start')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_learning_sessions_concept_id_concepts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index('ix_learning_sessions_concept_id_status', 'learning_sessions', ['concept_id', 'status'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_key', sa.String(length=100), nullable=False),
    sa.Column('prompt_snapshot_markdown', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('feedback_markdown', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_exercise_attempts_score_range')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_exercise_attempts_session_id_learning_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_attempts'))
    )
    op.create_index('ix_exercise_attempts_session_id_created_at', 'exercise_attempts', ['session_id', 'created_at'], unique=False)
    op.create_table('learning_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('code', 'document', 'diagram', 'benchmark', 'link')", name=op.f('ck_learning_artifacts_valid_artifact_type')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_learning_artifacts_session_id_learning_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_artifacts'))
    )
    op.create_table('session_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f('ck_session_messages_valid_role')),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_session_messages_positive_sequence_number')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_session_messages_session_id_learning_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_messages')),
    sa.UniqueConstraint('session_id', 'sequence_number', name='session_sequence_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_messages')
    op.drop_table('learning_artifacts')
    op.drop_index('ix_exercise_attempts_session_id_created_at', table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index('ix_learning_sessions_concept_id_status', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('concept_mastery')
    op.drop_table('concepts')
    op.drop_table('learning_modules')
    op.drop_table('learning_tracks')
    # ### end Alembic commands ###
